### ISSUE TITLE
Finding the BLE device name

### ISSUE THREAD

**Issue by claudiorrrr** [rbaron/catprinter#40]
This might be a silly question, but I'm not able to find the printer (Using MacOS). Is there any particular way to know what the name of the BLE device is?

**Comment by rbaron** [comment]
Hi @claudioruiz. You can use any BLE Scanner for that (e.g.: https://github.com/jnross/Bluetility on macOS or nRFConnect on iOS/Android).

Alternatively, I just pushed a commit that causes the script to try and auto-discover printers. Consider giving it a try!

**Comment by claudiorrrr** [comment]
Thanks about that! I'm afraid the issue I have is that for some reason my Macbook M1 is not able to detect the ble signal coming out from the printer. But using nRF Connect on iOS it does detect the signal and also the name of the device (in this case GB03), but I have had no luck with catprinter :(

Update: looking around on the internet it seems that the GB03 I have it's kind of a different model? Still, that doesn't answer the issue of not being detected by my mac.

**Comment by rbaron** [comment]
I added [this comment](https://github.com/rbaron/catprinter/issues/2#issuecomment-905801909) on #2 with the decompiled code that scans printers by name. "GB03" seems to be valid.

I would suggest using nRF connect or some other app on your macOS to try and connect to it. I'm curious to see what you find out.

**Comment by claudiorrrr** [comment]
This is quite odd indeed. I did install nRF Connect and it shows "No Devices Available", hence, I'm not able to scan anything. Yeah, bluetooth is active on the laptop. I'm really confused (not your fault, obviously!)
